"use client";
import Link from "next/link";
import {ReactNode,createContext,useCallback,useContext,useEffect,useId,useRef,useState} from "react";
type Toast={id:number;message:string};
const ToastContext=createContext<(message:string)=>void>(()=>{});
export function ToastProvider({children}:{children:ReactNode}){const[items,setItems]=useState<Toast[]>([]);const show=useCallback((message:string)=>{const id=Date.now()+Math.random();setItems(x=>[...x,{id,message}]);setTimeout(()=>setItems(x=>x.filter(t=>t.id!==id)),3500)},[]);return <ToastContext.Provider value={show}>{children}<div className="toast-region" aria-live="polite" aria-atomic="true">{items.map(t=><div className="toast" key={t.id}>{t.message}</div>)}</div></ToastContext.Provider>}
export const useToast=()=>useContext(ToastContext);
export function PageHeader({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}){return <header className="page-header"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="subtitle">{description}</p>}</div>{children&&<div className="actions">{children}</div>}</header>}
export function Breadcrumb({items}:{items:{label:string;href?:string}[]}){return <nav className="breadcrumb" aria-label="Breadcrumb"><ol>{items.map((item,index)=><li key={`${item.label}-${index}`}>{item.href?<Link href={item.href}>{item.label}</Link>:<span aria-current="page">{item.label}</span>}</li>)}</ol></nav>}
export function Alert({children,type="info"}:{children:ReactNode;type?:"info"|"success"|"error"}){return <div className={`alert ${type}`} role={type==="error"?"alert":"status"}>{children}</div>}
export function EmptyState({title="Belum ada data",children,action}:{title?:string;children?:ReactNode;action?:ReactNode}){return <div className="empty"><strong>{title}</strong>{children&&<p>{children}</p>}{action}</div>}
export function LoadingState({label="Memuat data"}:{label?:string}){return <div className="loading-stack" role="status"><span className="sr-only">{label}</span><div className="loading"/><div className="loading loading-short"/></div>}
export function ErrorState({message,onRetry}:{message:string;onRetry?:()=>void}){return <div className="error-state" role="alert"><strong>Data belum dapat dimuat</strong><p>{message}</p>{onRetry&&<button onClick={onRetry}>Coba lagi</button>}</div>}
export function StatusBadge({children,tone="neutral"}:{children:ReactNode;tone?:"neutral"|"success"|"warning"|"danger"}){return <span className={`badge ${tone}`}>{children}</span>}
function DialogFrame({title,children,onClose,alert=false}:{title:string;children:ReactNode;onClose:()=>void;alert?:boolean}){const titleId=useId(),descriptionId=useId(),box=useRef<HTMLElement>(null),previous=useRef<HTMLElement|null>(null);useEffect(()=>{previous.current=document.activeElement as HTMLElement;const focusable=()=>Array.from(box.current?.querySelectorAll<HTMLElement>('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')??[]);focusable()[0]?.focus();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();if(e.key==="Tab"){const items=focusable();if(!items.length)return;const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);previous.current?.focus()}},[onClose]);return <div className="modal-backdrop" onMouseDown={onClose}><section ref={box} className="modal" role={alert?"alertdialog":"dialog"} aria-modal="true" aria-labelledby={titleId} aria-describedby={descriptionId} onMouseDown={e=>e.stopPropagation()}><h2 id={titleId}>{title}</h2><div id={descriptionId}>{children}</div></section></div>}
export function ConfirmDialog({title,children,onClose,onConfirm,confirmLabel="Konfirmasi",busy=false}:{title:string;children:ReactNode;onClose:()=>void;onConfirm:()=>void;confirmLabel?:string;busy?:boolean}){return <DialogFrame title={title} onClose={onClose} alert><p>{children}</p><div className="modal-footer"><button onClick={onClose} disabled={busy}>Batal</button><button className="danger" onClick={onConfirm} disabled={busy}>{busy?"Memproses…":confirmLabel}</button></div></DialogFrame>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <DialogFrame title={title} onClose={onClose}>{children}</DialogFrame>}
export function CheckIcon(){return <svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="m5 12 4 4L19 6"/></svg>}
