"use client";
import Link from "next/link";import {ReactNode,createContext,useContext,useEffect,useRef,useState} from "react";
type Toast={id:number;message:string};const ToastContext=createContext<(message:string)=>void>(()=>{});
export function ToastProvider({children}:{children:ReactNode}){const[items,setItems]=useState<Toast[]>([]);const show=(message:string)=>{const id=Date.now();setItems(x=>[...x,{id,message}]);setTimeout(()=>setItems(x=>x.filter(t=>t.id!==id)),3500)};return <ToastContext.Provider value={show}>{children}<div className="toast-region" aria-live="polite">{items.map(t=><div className="toast" key={t.id}>{t.message}</div>)}</div></ToastContext.Provider>}
export const useToast=()=>useContext(ToastContext);
export function PageHeader({eyebrow,title,description,children}:{eyebrow?:string;title:string;description?:string;children?:ReactNode}){return <header className="page-header"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="subtitle">{description}</p>}</div>{children&&<div className="actions">{children}</div>}</header>}
export function Breadcrumb({items}:{items:{label:string;href?:string}[]}){return <nav className="breadcrumb" aria-label="Breadcrumb">{items.map((item,index)=><span key={item.label}>{item.href?<Link href={item.href}>{item.label}</Link>:<span aria-current="page">{item.label}</span>}{index<items.length-1&&<b>/</b>}</span>)}</nav>}
export function Alert({children,type="info"}:{children:ReactNode;type?:"info"|"success"|"error"}){return <p className={`alert ${type==="info"?"":type}`} role="status" aria-live="polite">{children}</p>}
export function ConfirmDialog({title,children,onClose,onConfirm,confirmLabel="Konfirmasi",busy=false}:{title:string;children:ReactNode;onClose:()=>void;onConfirm:()=>void;confirmLabel?:string;busy?:boolean}){const confirmRef=useRef<HTMLButtonElement>(null);useEffect(()=>{confirmRef.current?.focus();const key=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[onClose]);return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="alertdialog" aria-modal="true" aria-labelledby="confirm-title" onMouseDown={e=>e.stopPropagation()}><h2 id="confirm-title">{title}</h2><p>{children}</p><div className="modal-footer"><button onClick={onClose} disabled={busy}>Batal</button><button ref={confirmRef} className="danger" onClick={onConfirm} disabled={busy}>{busy?"Memproses…":confirmLabel}</button></div></section></div>}
export function EmptyState({children}:{children:ReactNode}){return <div className="empty">{children}</div>};export function LoadingState(){return <div className="loading" aria-label="Memuat data"/>}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){return <div className="modal-backdrop" role="presentation" onMouseDown={onClose}><section className="modal" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>e.stopPropagation()}><h2>{title}</h2>{children}</section></div>}
