"use client";
import {useState} from "react";
import {ArrowRight,BookOpen,Eye,EyeOff} from "lucide-react";
import {api,errorMessage,jsonRequest} from "@/lib/client-api";
import {Alert} from "@/app/ui";
export default function Login(){
  const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[show,setShow]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/auth/login",jsonRequest("POST",{email,password}));location.href="/dashboard"}catch(e){setError(errorMessage(e));setBusy(false)}}
  return <main className="app"><div className="auth-layout"><section className="auth-story"><BookOpen size={36} strokeWidth={1.5} aria-hidden="true"/><p className="eyebrow section-gap">PIB Penilaian</p><h2>Lebih mudah menilai.<br/>Lebih jelas memantau.</h2><p>Ruang kerja penilaian Praktik Ibadah. Kelola siswa, catat hasil, dan siapkan laporan dalam satu tempat.</p></section><section className="auth-form"><p className="eyebrow">Selamat datang kembali</p><h1>Masuk ke ruang kerja</h1><p className="subtitle">Gunakan akun guru untuk melanjutkan penilaian.</p><form className="section-stack section-gap" aria-busy={busy} onSubmit={submit}><div className="field"><label htmlFor="email">Email</label><input id="email" type="email" autoComplete="username" placeholder="nama@sekolah.sch.id" value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="field"><label htmlFor="password">Password</label><div className="password-control"><input id="password" type={show?"text":"password"} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><button type="button" aria-label={show?"Sembunyikan password":"Tampilkan password"} aria-pressed={show} onClick={()=>setShow(v=>!v)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></div>{error&&<Alert type="error">{error}</Alert>}<button className="primary" disabled={busy}>{busy?"Memeriksa akun…":"Masuk"}<ArrowRight size={16}/></button><p className="hint">Akun dikelola oleh pengelola aplikasi di sekolah Anda.</p></form></section></div></main>;
}
