"use client";
import { useEffect, useState } from "react";
import ExcelJS from "exceljs";
type R = Record<string, any>;
type ImportRow = { classId: number; nis?: string; name: string; gender?: "" | "L" | "P" };
export default function Students() { const [students,setStudents]=useState<R[]>([]),[classes,setClasses]=useState<R[]>([]),[msg,setMsg]=useState(""),[preview,setPreview]=useState<ImportRow[]>([]); const load=()=>Promise.all([fetch("/api/students").then(r=>r.json()),fetch("/api/classes").then(r=>r.json())]).then(([s,c])=>{setStudents(s);setClasses(c)}); useEffect(()=>{load()},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const r=await fetch("/api/students",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({classId:Number(f.get("classId")),nis:f.get("nis"),name:f.get("name"),gender:f.get("gender")})});setMsg(r.ok?"Siswa tersimpan.":(await r.json()).error);if(r.ok){form.reset();load()}}
 async function readFile(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;let rows:ImportRow[]=[];if(file.name.toLowerCase().endsWith(".xlsx")){const book=new ExcelJS.Workbook();await book.xlsx.load(await file.arrayBuffer());const sheet=book.worksheets[0];sheet.eachRow((row,n)=>{if(n>1)rows.push({classId:Number(row.getCell(1).value),nis:String(row.getCell(2).value??""),name:String(row.getCell(3).value??""),gender:(String(row.getCell(4).value??"") as ""|"L"|"P")})})}else{rows=(await file.text()).split(/\r?\n/).filter(Boolean).slice(1).map(line=>{const [classId,nis,name,gender]=line.split(",");return {classId:Number(classId),nis,name,gender:(gender??"") as ""|"L"|"P"}})}setPreview(rows);setMsg(`${rows.length} baris siap diimpor. Periksa preview lalu commit.`);e.target.value=""}
 async function commitImport(){const r=await fetch("/api/students/import",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(preview)});const x=await r.json();setMsg(r.ok?`${x.imported} siswa diimpor; ${x.failed.length} baris gagal.`:x.error);setPreview([]);load()}
 async function edit(x:R){const name=prompt("Nama siswa",x.name)?.trim();if(!name||name===x.name)return;const r=await fetch(`/api/students?id=${x.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({classId:x.class_id,nis:x.nis??"",name,gender:x.gender??""})});setMsg(r.ok?"Siswa diperbarui.":(await r.json()).error);load()}
 async function remove(id:number){if(!confirm("Nonaktifkan siswa ini?"))return;const r=await fetch(`/api/students?id=${id}`,{method:"DELETE"});setMsg(r.ok?"Siswa dinonaktifkan.":(await r.json()).error);load()}
 async function destroy(id:number){if(!confirm("Hapus permanen siswa ini? Tindakan ini tidak dapat dibatalkan."))return;const r=await fetch(`/api/students?id=${id}&permanent=1`,{method:"DELETE"});setMsg(r.ok?"Siswa dihapus.":(await r.json()).error);load()}
 return <main className="app"><h1>Data siswa</h1><p className="subtitle">Tambah, edit, impor, dan kelola siswa aktif.</p>{msg&&<p className="notice">{msg}</p>}<section className="card"><form onSubmit={submit}><div className="row"><select name="classId" required><option value="">Pilih kelas</option>{classes.map(x=><option key={x.id} value={x.id}>{x.name} · {x.academic_year_name}</option>)}</select><input name="nis" placeholder="NIS"/><input name="name" placeholder="Nama siswa" required/><select name="gender"><option value="">Gender</option><option value="L">L</option><option value="P">P</option></select><button className="primary">Tambah siswa</button></div></form><label className="button">Pilih CSV/XLSX<input hidden type="file" accept=".csv,.txt,.xlsx" onChange={readFile}/></label><p className="notice">Kolom: classId, nis, nama, gender. Baris pertama dianggap header.</p>{preview.length>0&&<div><h3>Preview ({preview.length} baris)</h3><div style={{overflowX:"auto"}}><table><tbody>{preview.slice(0,20).map((x,i)=><tr key={i}><td>{x.classId}</td><td>{x.nis}</td><td>{x.name}</td><td>{x.gender}</td></tr>)}</tbody></table></div><button className="primary" onClick={commitImport}>Commit impor</button><button onClick={()=>setPreview([])}>Batal</button></div>}</section><section className="card" style={{marginTop:18}}><h2>Daftar siswa ({students.length})</h2>{students.length?<div style={{overflowX:"auto"}}><table><thead><tr><th>NIS</th><th>Nama</th><th>Kelas</th><th>Gender</th><th>Aksi</th></tr></thead><tbody>{students.map(x=><tr key={x.id}><td>{x.nis||"—"}</td><td>{x.name}</td><td>{x.class_name}</td><td>{x.gender||"—"}</td><td><button onClick={()=>edit(x)}>Edit</button> <button onClick={()=>remove(x.id)}>Nonaktifkan</button> <button onClick={()=>destroy(x.id)}>Hapus</button></td></tr>)}</tbody></table></div>:<div className="empty">Belum ada siswa.</div>}</section></main> }
