"use client";
import {useCallback,useEffect,useState} from "react";
import {Plus,Save} from "lucide-react";
import {api,errorMessage,jsonRequest} from "@/lib/client-api";
import {AcademicYear,Settings} from "@/lib/frontend-types";
import {Alert,EmptyState,ErrorState,LoadingState,Modal,PageHeader,StatusBadge,useToast} from "@/app/ui";
export default function MasterData(){
  const [years,setYears]=useState<AcademicYear[]>([]),[settings,setSettings]=useState<Settings>({});
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[adding,setAdding]=useState(false);
  const [error,setError]=useState(""),[formError,setFormError]=useState(""),[yearError,setYearError]=useState("");
  const toast=useToast();
  const load=useCallback(async()=>{setLoading(true);setError("");try{const [y,s]=await Promise.all([api<AcademicYear[]>("/api/academic-years"),api<Settings>("/api/settings")]);setYears(y);setSettings(s)}catch(e){setError(errorMessage(e))}finally{setLoading(false)}},[]);
  useEffect(()=>{void load()},[load]);
  async function addYear(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setYearError("");const f=new FormData(e.currentTarget);try{await api("/api/academic-years",jsonRequest("POST",{name:f.get("name"),semester:f.get("semester"),isActive:true}));setAdding(false);toast("Tahun ajaran berhasil ditambahkan.");await load()}catch(e){setYearError(errorMessage(e))}finally{setBusy(false)}}
  async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setFormError("");try{await api("/api/settings",jsonRequest("PUT",settings));window.dispatchEvent(new Event("pib-settings-change"));toast("Identitas sekolah berhasil disimpan.")}catch(e){setFormError(errorMessage(e))}finally{setBusy(false)}}
  return <main className="app"><PageHeader eyebrow="Pengaturan ruang kerja" title="Sekolah & tahun ajaran" description="Identitas sekolah dan periode yang digunakan pada laporan resmi."/>{loading?<LoadingState/>:error?<ErrorState message={error} onRetry={load}/>:<div className="dashboard-main-grid"><form className="card" aria-busy={busy} onSubmit={save}><h2>Identitas sekolah</h2><p className="subtitle">Informasi ini tampil pada laporan penilaian.</p><div className="section-stack section-gap"><div className="field"><label htmlFor="school-name">Nama sekolah</label><input id="school-name" value={settings.schoolName??""} onChange={e=>setSettings({...settings,schoolName:e.target.value})}/></div><div className="field"><label htmlFor="school-address">Alamat sekolah</label><textarea id="school-address" value={settings.schoolAddress??""} onChange={e=>setSettings({...settings,schoolAddress:e.target.value})}/></div><div className="field"><label htmlFor="teacher-name">Nama guru atau penilai</label><input id="teacher-name" value={settings.teacherName??""} onChange={e=>setSettings({...settings,teacherName:e.target.value})}/></div></div>{formError&&<Alert type="error">{formError}</Alert>}<div className="form-actions"><button className="primary" disabled={busy}><Save size={15}/>{busy?"Menyimpan…":"Simpan identitas"}</button></div></form><section className="card"><div className="section-heading"><h2>Tahun ajaran</h2><button type="button" className="icon-button" aria-label="Tambah periode" onClick={()=>{setYearError("");setAdding(true)}}><Plus size={17}/></button></div><p className="subtitle">Kelompokkan kelas dan materi per periode.</p>{years.length?<div className="chapter-list">{years.map(y=><div className="chapter-item" key={y.id}><div className="chapter-copy"><strong>{y.name}</strong><small>Semester {y.semester}</small></div><StatusBadge tone={y.is_active?"success":"neutral"}>{y.is_active?"Aktif":"Arsip"}</StatusBadge></div>)}</div>:<EmptyState title="Belum ada tahun ajaran" action={<button className="primary" onClick={()=>setAdding(true)}>Tambah periode</button>}>Siapkan periode pertama untuk mulai mengelola kelas.</EmptyState>}</section></div>}{adding&&<Modal title="Tambah tahun ajaran" busy={busy} onClose={()=>setAdding(false)}><form className="section-stack" onSubmit={addYear}><div className="field"><label htmlFor="year-name">Tahun ajaran</label><input id="year-name" name="name" placeholder="Contoh: 2026/2027" minLength={4} maxLength={20} required/></div><div className="field"><label htmlFor="year-semester">Semester</label><select id="year-semester" name="semester"><option>Ganjil</option><option>Genap</option></select></div>{yearError&&<Alert type="error">{yearError}</Alert>}<div className="modal-footer"><button type="button" disabled={busy} onClick={()=>setAdding(false)}>Batal</button><button className="primary" disabled={busy}>{busy?"Menambahkan…":"Tambah periode"}</button></div></form></Modal>}</main>;
}
